Tag:Value reference fix.
OpenChain-Project/Telco-WG pull request #32
Opened 2022-12-30 15:48 UTC by Jimmy-ahlberg

Fixing the naming of Tag:Value and inserting a reference to the SPDX specification.

2023-01-09 08:21 UTC, CsatariGergely requested changes

2023-01-09 08:21 UTC, CsatariGergely commented on OpenChain Telco SBOM Specification.md
> +Tag:Value is described here in SPDX 2.2 https://spdx.github.io/spdx-spec/v2.2.2/conformance/#44-standard-data-format-requirements
```suggestion
Tag:Value is described in section 4.4, Standard data format requirements of the SPDX 2.2 specification ([https://spdx.github.io/spdx-spec/v2.2.2/conformance/#44-standard-data-format-requirements](https://spdx.github.io/spdx-spec/v2.2.2/conformance/#44-standard-data-format-requirements))
```

2023-01-09 08:21 UTC, CsatariGergely commented on OpenChain Telco SBOM Specification.md
> +Tag:Value is described here in SPDX 2.2 https://spdx.github.io/spdx-spec/v2.2.2/conformance/#44-standard-data-format-requirements
```suggestion
Tag:Value is described in section 4.4, Standard data format requirements of the SPDX 2.2 specification ([https://spdx.github.io/spdx-spec/v2.2.2/conformance/#44-standard-data-format-requirements](https://spdx.github.io/spdx-spec/v2.2.2/conformance/#44-standard-data-format-requirements))
```

2023-01-09 17:38 UTC, winterrocks commented on OpenChain Telco SBOM Specification.md
> +To facilitate a simplified toolchain, a machine readable version of the SBOM needs to be included. To ensure repeatability and harmonization a conformant SBOM must be in the Tag:Value format. An enti
As above using ":" seems to be the way.

2023-02-02 08:24 UTC, vargenau commented on OpenChain Telco SBOM Specification.md
> +Tag:Value is described here in SPDX 2.2 https://spdx.github.io/spdx-spec/v2.2.2/conformance/#44-standard-data-format-requirements
We decided that it was safer for the moment to use the ISO version of SPDX.

2023-02-02 08:24 UTC, merged