Update OpenChain Telco SBOM Specification.md
OpenChain-Project/Telco-WG pull request #34
Opened 2022-12-30 17:17 UTC by Jimmy-ahlberg

Added some proposed language for us to discuss.

2022-12-30 17:18 UTC, Jimmy-ahlberg commented
This also leaves open the discussion on if we see a value to investigate possible trademarks for the SBOM specification.

2023-01-09 08:13 UTC, CsatariGergely requested changes

2023-01-09 08:13 UTC, CsatariGergely commented on OpenChain Telco SBOM Specification.md
> +To indicate that the software has a conformant SBOM available, you may use the following statement: "This software is supplied with a SBOM conformant to the OpenChain Telco SBOM Specification v1.0, T
```suggestion
To indicate that the software has a conformant SBOM available, you may use the following statement: "This software is supplied with a SBOM conformant to the OpenChain Telco SBOM Specification v1.0, The specification is available at [Insert homepage]"
```

2023-01-09 08:13 UTC, CsatariGergely commented on OpenChain Telco SBOM Specification.md
> +You may at your choosing use the following statement in you Telco Speficatation conformant SBOM “This SBOM conforms to the OpenChain Telco SBOM specification v1.0 [Inser homepage], it is provided to
```suggestion
You may at your choosing use the following statement in you Telco Speficatation conformant SBOM “This SBOM conforms to the OpenChain Telco SBOM specification v1.0 [Insert homepage], it is provided to the recipient free of charge, and the recipient is free to redistribute this SBOM to any 3rd that they distribute the corresponding software to, provided that they have all the necessary right to distribute the software to such 3rd party"
```

2023-01-09 17:31 UTC, winterrocks commented on OpenChain Telco SBOM Specification.md
> +To indicate that the software has a conformant SBOM available, you may use the following statement: "This software is supplied with a SBOM conformant to the OpenChain Telco SBOM Specification v1.0, T
Just a typo fix.

2023-01-09 17:31 UTC, winterrocks commented on OpenChain Telco SBOM Specification.md
> +You may at your choosing use the following statement in you Telco Speficatation conformant SBOM “This SBOM conforms to the OpenChain Telco SBOM specification v1.0 [Inser homepage], it is provided to
Typo fixes.

2023-02-02 08:21 UTC, merged